import axios from "axios";
import * as cheerio from "cheerio";
import { Exchange } from "./types";
import { getCached, setCached, getStale, setStaleFallback } from "./cache";

/**
 * ACKNOWLEDGMENT (required by the assignment brief):
 * Google Finance has NO public API at all — official or unofficial-library-wrapped.
 * The only option is scraping the rendered HTML of a Google Finance quote page,
 * e.g. https://www.google.com/finance/quote/HDFCBANK:NSE
 *
 * WHY THIS IS FRAGILE (be ready to say this out loud in the interview):
 * 1. Google Finance's page is a React/JS-heavy app. Its class names (e.g. "P6K39c")
 *    are auto-generated by a CSS-in-JS build step and can change on every Google
 *    deploy, with no versioning or changelog for scrapers to follow.
 * 2. Google can serve different markup to a server-side request (no browser,
 *    no JS execution) than to a real browser, if the page relies on
 *    client-side rendering for some fields.
 * 3. Google can rate-limit or block server IPs that make many rapid requests
 *    without the headers/cookies a real browser sends.
 *
 * MITIGATION STRATEGY USED HERE:
 * - We search for label text ("P/E ratio") rather than hardcoding a specific
 *   CSS class, and read the *next* sibling's text as the value. This is more
 *   resilient to class-name churn than a hardcoded selector, though it will
 *   still break if Google changes the label wording or page structure entirely.
 * - Every failure falls back to the last successfully cached value (see
 *   cache.ts) instead of showing a blank or crashing the row.
 * - Results are cached (see CACHE_TTL_MS) so we do not re-scrape on every
 *   15-second UI refresh — only when the cache actually expires.
 *
 * IN A REAL PRODUCT, the right long-term fix is a paid data provider
 * (e.g. NSE/BSE licensed feeds, or a paid tier of a financial data API)
 * rather than scraping — this implementation is intentionally built to
 * satisfy the assignment's explicit ask to "propose solutions (e.g.
 * scraping or unofficial libraries)" and reason about their limitations.
 */

function toGoogleFinanceSymbol(code: string, exchange: Exchange): string {
  return `${code}:${exchange}`;
}

export interface GoogleFinanceResult {
  peRatio: number | null;
  latestEarnings: number | null;
  stale: boolean;
  error?: string;
}

/**
 * Finds a numeric value on the page associated with a given label,
 * by scanning for elements whose text matches the label and reading
 * the next element's text as the value. See the fragility note above.
 */
function extractLabeledNumber($: cheerio.CheerioAPI, label: string): number | null {
  let result: number | null = null;

  $("div").each((_, el) => {
    if (result !== null) return; // already found, skip rest

    const text = $(el).text().trim().toLowerCase();
    if (text === label.toLowerCase()) {
      const valueText = $(el).next().text().trim();
      const parsed = parseFloat(valueText.replace(/,/g, ""));
      if (!Number.isNaN(parsed)) {
        result = parsed;
      }
    }
  });

  return result;
}

export async function fetchGoogleFinanceStats(
  code: string,
  exchange: Exchange
): Promise<GoogleFinanceResult> {
  const cacheKey = `google:${code}`;
  const cached = getCached<{ peRatio: number | null; latestEarnings: number | null }>(cacheKey);
  if (cached !== undefined) {
    return { ...cached, stale: false };
  }

  const symbol = toGoogleFinanceSymbol(code, exchange);
  const url = `https://www.google.com/finance/quote/${symbol}`;

  try {
    const response = await axios.get(url, {
      timeout: 8000,
      headers: {
        // A real browser User-Agent reduces (does not eliminate) the chance
        // of being served a bot-detection page instead of real content.
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36",
      },
    });

    const $ = cheerio.load(response.data);

    const peRatio = extractLabeledNumber($, "P/E ratio");
    // Google Finance's quote page does not reliably expose a labeled
    // "Latest Earnings" (EPS) field the way Yahoo does — this is a known
    // gap, documented in TECHNICAL_DOCUMENT.md. We attempt an "EPS" label
    // as a best-effort secondary source.
    const latestEarnings = extractLabeledNumber($, "EPS");

    const result = { peRatio, latestEarnings };
    setCached(cacheKey, result);
    setStaleFallback(cacheKey, result);

    return { ...result, stale: false };
  } catch (err) {
    const stale = getStale<{ peRatio: number | null; latestEarnings: number | null }>(cacheKey);
    return {
      peRatio: stale?.peRatio ?? null,
      latestEarnings: stale?.latestEarnings ?? null,
      stale: stale !== undefined,
      error: err instanceof Error ? err.message : "Unknown Google Finance error",
    };
  }
}
